---
title: 서울시 생활인구 데이터 분석3 [데이터 분석] 
author: JDW
date: '2020-04-16'
slug: seoulpop3
categories:
  - 데이터분석
tags:
  - R
---



<p><img src="/post/2020-04-16-seoulpop3_files/seoul-410264_1920.jpg" /></p>
<p>  지금까지 서울시에서 제공하는 공공데이터인 서울시 주민등록 인구 통계 데이터를 호출하여 전처리하는 과정까지 진행하였습니다. 분석의 마무리 과정으로 간단히 그래프를 그려 서울시 인구의 추세와 동향을 살펴보겠습니다.
<br></p>
<div id="데이터-분석" class="section level1">
<h1>데이터 분석</h1>
<div id="데이터-호출" class="section level2">
<h2>데이터 호출</h2>
<p>  먼저 이전 장에서 전처리한 데이터를 불러와 줍니다.</p>
<pre class="r"><code>sum_seouldata &lt;- readRDS(&#39;./sum_seouldata.rds&#39;)
seouldata &lt;- readRDS(&#39;./seouldata.rds&#39;)</code></pre>
<pre class="r"><code>head(sum_seouldata); head(seouldata);</code></pre>
<pre><code>##    GIGAN JACHIGU   SEDAE    GYE_1 NAMJA_1 YEOJA_1    GYE_2 NAMJA_2 YEOJA_2
## 1 2010-1    합계 4121193 10464171 5181117 5283054 10208670 5059504 5149166
## 2 2010-2    합계 4116225 10447719 5172523 5275196 10194327 5051806 5142521
## 3 2010-3    합계 4114216 10437326 5165474 5271852 10186556 5046415 5140141
## 4 2010-4    합계 4224181 10575447 5236742 5338705 10312545 5111259 5201286
## 5 2011-1    합계 4221613 10581728 5238674 5343054 10307783 5107011 5200772
## 6 2011-2    합계 4210104 10570064 5231751 5338313 10288284 5095751 5192533
##    GYE_3 NAMJA_3 YEOJA_3 SEDAEDANGINGU N_65SEISANGGORYEONGJA year qrt
## 1 255501  121613  133888          2.48                956414 2010   1
## 2 253392  120717  132675          2.48                966441 2010   2
## 3 250770  119059  131711          2.48                974256 2010   3
## 4 262902  125483  137419          2.44               1007572 2010   4
## 5 273945  131663  142282          2.44               1018534 2011   1
## 6 281780  136000  145780          2.44               1025615 2011   2</code></pre>
<pre><code>##    GIGAN  JACHIGU  SEDAE  GYE_1 NAMJA_1 YEOJA_1  GYE_2 NAMJA_2 YEOJA_2 GYE_3
## 1 2010-1   종로구  74300 177023   88225   88798 168158   84088   84070  8865
## 2 2010-1     중구  58472 138102   69175   68927 129786   65216   64570  8316
## 3 2010-1   용산구 107407 250844  123295  127549 238366  116764  121602 12478
## 4 2010-1   성동구 126942 316113  158228  157885 308144  154389  153755  7969
## 5 2010-1   광진구 156264 386292  190823  195469 373586  185087  188499 12706
## 6 2010-1 동대문구 153517 374039  187583  186456 361812  182250  179562 12227
##   NAMJA_3 YEOJA_3 SEDAEDANGINGU N_65SEISANGGORYEONGJA year qrt
## 1    4137    4728          2.26                 20925 2010   1
## 2    3959    4357          2.22                 16208 2010   1
## 3    6531    5947          2.22                 28436 2010   1
## 4    3839    4130          2.43                 30704 2010   1
## 5    5736    6970          2.39                 30765 2010   1
## 6    5333    6894          2.36                 40300 2010   1</code></pre>
</div>
<div id="변수열-선택" class="section level2">
<h2>변수열 선택</h2>
<p>  불러온 데이터 중 분석에 사용할 데이터 변수열을 선택합니다. 이번에 사용할 데이터 변수들은 다음과 같습니다.</p>
<pre class="r"><code>sum_seouldata &lt;- sum_seouldata %&gt;% select(
    GIGAN,                  # 연도-분기 
    JACHIGU,                # 자치구 
    SEDAE,                  # 세대 
    GYE_1,                  # 전체 인구 
    NAMJA_1,                # 남성 인구 
    YEOJA_1,                # 여성 인구 
    SEDAEDANGINGU,          # 세대당 인구 
    N_65SEISANGGORYEONGJA,  # 65세 이상 인구 (고령 인구) 
    year,                   # 연도 
    qrt,                    # 분기 
)
seouldata &lt;- seouldata %&gt;% select(
    GIGAN,                  # 연도-분기 
    JACHIGU,                # 자치구 
    SEDAE,                  # 세대 
    GYE_1,                  # 전체 인구 
    NAMJA_1,                # 남성 인구 
    YEOJA_1,                # 여성 인구 
    SEDAEDANGINGU,          # 세대당 인구 
    N_65SEISANGGORYEONGJA,  # 65세 이상 인구 (고령 인구) 
    year,                   # 연도 
    qrt,                    # 분기 
)

head(sum_seouldata); head(seouldata)</code></pre>
<pre><code>##    GIGAN JACHIGU   SEDAE    GYE_1 NAMJA_1 YEOJA_1 SEDAEDANGINGU
## 1 2010-1    합계 4121193 10464171 5181117 5283054          2.48
## 2 2010-2    합계 4116225 10447719 5172523 5275196          2.48
## 3 2010-3    합계 4114216 10437326 5165474 5271852          2.48
## 4 2010-4    합계 4224181 10575447 5236742 5338705          2.44
## 5 2011-1    합계 4221613 10581728 5238674 5343054          2.44
## 6 2011-2    합계 4210104 10570064 5231751 5338313          2.44
##   N_65SEISANGGORYEONGJA year qrt
## 1                956414 2010   1
## 2                966441 2010   2
## 3                974256 2010   3
## 4               1007572 2010   4
## 5               1018534 2011   1
## 6               1025615 2011   2</code></pre>
<pre><code>##    GIGAN  JACHIGU  SEDAE  GYE_1 NAMJA_1 YEOJA_1 SEDAEDANGINGU
## 1 2010-1   종로구  74300 177023   88225   88798          2.26
## 2 2010-1     중구  58472 138102   69175   68927          2.22
## 3 2010-1   용산구 107407 250844  123295  127549          2.22
## 4 2010-1   성동구 126942 316113  158228  157885          2.43
## 5 2010-1   광진구 156264 386292  190823  195469          2.39
## 6 2010-1 동대문구 153517 374039  187583  186456          2.36
##   N_65SEISANGGORYEONGJA year qrt
## 1                 20925 2010   1
## 2                 16208 2010   1
## 3                 28436 2010   1
## 4                 30704 2010   1
## 5                 30765 2010   1
## 6                 40300 2010   1</code></pre>
<p><br></p>
</div>
<div id="상관-분석" class="section level2">
<h2>상관 분석</h2>
<p>  데이터 중 인구수를 의미하는 수치형 데이터들(남성인구, 여성인구 등) 간의 상관 분석을 진행합니다.</p>
<pre class="r"><code># 상관분석
cor_seoul &lt;- seouldata %&gt;%
    select(SEDAE, GYE_1, NAMJA_1, YEOJA_1, SEDAEDANGINGU, N_65SEISANGGORYEONGJA)
cor(cor_seoul, method = &#39;pearson&#39;) # 피어슨 상관 계수 </code></pre>
<pre><code>##                           SEDAE     GYE_1   NAMJA_1   YEOJA_1 SEDAEDANGINGU
## SEDAE                 1.0000000 0.9758178 0.9748451 0.9740954     0.3994059
## GYE_1                 0.9758178 1.0000000 0.9985342 0.9986800     0.5744186
## NAMJA_1               0.9748451 0.9985342 1.0000000 0.9944361     0.5699320
## YEOJA_1               0.9740954 0.9986800 0.9944361 1.0000000     0.5771191
## SEDAEDANGINGU         0.3994059 0.5744186 0.5699320 0.5771191     1.0000000
## N_65SEISANGGORYEONGJA 0.8385201 0.7976777 0.7892446 0.8035183     0.2736345
##                       N_65SEISANGGORYEONGJA
## SEDAE                             0.8385201
## GYE_1                             0.7976777
## NAMJA_1                           0.7892446
## YEOJA_1                           0.8035183
## SEDAEDANGINGU                     0.2736345
## N_65SEISANGGORYEONGJA             1.0000000</code></pre>
<p><br></p>
<p>  각 변수간의 상관성을 살펴보기 위해 R의 통계 내장함수 중 상관계수를 계산해주는 <code>cor()</code>함수를 사용하여 변수들의 상관성을 도출했습니다. 보통 계수가 0.7 이상이면 강한 상관관계에 있다고 볼 수 있는데요. 계산을 통해 세대당 인구를 제외한 나머지 인구 변수들간 상관성이 높다는 것을 도출할 수 있습니다.</p>
<p>  <strong><code>GGally</code></strong> 패키지의 <code>ggpair()</code>함수를 통해 상관분석의 차트를 그릴 수 있습니다. 인구변수간의 상관성을 시각화하여 살펴보도록 하겠습니다.</p>
<pre class="r"><code>library(GGally)
ggpairs(cor_seoul)</code></pre>
<p><img src="/post/2020-04-16-seoulpop3_files/figure-html/unnamed-chunk-6-1.png" width="100%" />
<br></p>
<p>  차트는 총 세가지의 범주의 정보를 포함하고 있습니다. 차트의 좌-하단부는 변수간의 산점도를 나타내고, 우-상단부엔 앞서 계산했던 변수간의 상관 계수가 표시됩니다. 중앙에는 각 변수의 분포가 그려져 이를 파악할 수 있습니다.</p>
<p>  상관 계수를 숫자로만 보았을 때 보다 확실히 시각화를 진행하니 더욱 직관적으로 다가오는 부분이 있네요. 세대당 인구수를 제외한 나머지 변수들의 상관성이 높게 나타나는것은 물론이고, 남성인구와 여성인구의 상관성도 0.994로 1에 근접하는 굉장히 높은 수치인 걸 볼 수 있습니다. 65세 이상 인구에 있어서는 남성 인구와의 상관계수(0.789) 보다 여성 인구와의 상관계수(0.804)가 더 높은걸로 보아 고령인구에는 남자보다 여자가 더 많이 분포되어 있을 것으로 판단됩니다.</p>
<p>  이 밖에도 R에서는 <strong><code>corrplot</code></strong>, <strong><code>PerformanceAnalytics</code></strong>등의 패키지를 통해 상관분석 그래프를 그릴 수 있습니다.</p>
</div>
<div id="인구-동향" class="section level2">
<h2>인구 동향</h2>
<p>  이번에는 앞서 전처리한 데이터를 기반으로 그래프를통해 서울시의 인구의 동향을 파악해 보도록 합시다. 주로 라인 그래프를 그려 기간별 동향을 파악할 것입니다.
<br></p>
<div id="서울시-전체-인구" class="section level3">
<h3>서울시 전체 인구</h3>
<pre class="r"><code>library(ggplot2)

# 연도별 인구
sum_seouldata %&gt;%
    group_by(year) %&gt;%
    summarise(mean_pop = round(mean(GYE_1), 0)) %&gt;%
    ggplot(aes(x = year %&gt;% as.factor(), y = mean_pop, group = 1)) +
    geom_point(color = &#39;red&#39;) +
    geom_line() +
    geom_text(aes(label = mean_pop), hjust = &#39;inward&#39;, vjust = &#39;inward&#39;, size = 4, angle = 15) +
    theme(title = element_text(face = &#39;bold&#39;, size = 25)) +
    theme(axis.text.x = element_text(angle = 45)) +
    theme(axis.title.x = element_text(size = 15)) +
    theme(axis.title.y = element_text(size = 15)) +
    labs(title = &#39;서울시 연평균 인구수 변화 추이&#39;,
         x = &#39;연도&#39;, y = &#39;인구&#39;)</code></pre>
<p><img src="/post/2020-04-16-seoulpop3_files/figure-html/unnamed-chunk-7-1.png" width="100%" /></p>
<pre class="r"><code># 연도-분기별 인구
sum_seouldata %&gt;%
    ggplot(aes(x = GIGAN, y = GYE_1, group = 1)) +
    geom_point(color = &#39;red&#39;) +
    geom_line() +
    geom_text(aes(label = GYE_1), hjust = &#39;inward&#39;, vjust = &#39;inward&#39;, size = 2, angle = 15) +
    theme(title = element_text(face = &#39;bold&#39;, size = 25)) +
    theme(axis.text.x = element_text(angle = 45)) +
    theme(axis.title.x = element_text(size = 15)) +
    theme(axis.title.y = element_text(size = 15)) +
    labs(title = &#39;연도-분기별 서울시 인구수 변화 추이&#39;,
         x = &#39;연도-분기&#39;, y = &#39;인구수&#39;) </code></pre>
<p><img src="/post/2020-04-16-seoulpop3_files/figure-html/unnamed-chunk-7-2.png" width="100%" /></p>
<pre class="r"><code>sum_seouldata %&gt;%
    mutate(tempyear = paste(year, &#39;년&#39;)) %&gt;%
    ggplot(aes(x = qrt %&gt;% as.factor(), y = GYE_1, group = 1)) +
    geom_point(color = &#39;red&#39;) +
    geom_line() +
    geom_text(aes(label = GYE_1), hjust = &#39;inward&#39;, vjust = &#39;inward&#39;, size = 2, angle = 15) +
    theme(title = element_text(face = &#39;bold&#39;, size = 25)) +
    theme(axis.title.x = element_text(size = 15)) +
    theme(axis.title.y = element_text(size = 15)) +
    labs(title = &#39;연도-분기별 서울시 인구수 변화 추이&#39;,
         x = &#39;분기&#39;, y = &#39;인구수&#39;) +
    facet_grid(~tempyear)</code></pre>
<p><img src="/post/2020-04-16-seoulpop3_files/figure-html/unnamed-chunk-7-3.png" width="100%" /></p>
<pre class="r"><code># 분기별 인구수 변화
sum_seouldata %&gt;%
    mutate(tempqrt = paste(qrt, &#39;분기&#39;)) %&gt;%
    ggplot(aes(x =year %&gt;% as.factor(), y = GYE_1, group = 1)) +
    geom_point(color = &#39;red&#39;) +
    geom_line() +
    geom_text(aes(label = GYE_1), hjust = &#39;inward&#39;, vjust = &#39;inward&#39;, size = 3, angle = 15) +
    theme(title = element_text(face = &#39;bold&#39;, size = 25)) +
    theme(axis.text.x = element_text(angle = 45)) +
    theme(axis.title.x = element_text(size = 15)) +
    theme(axis.title.y = element_text(size = 15)) +
    labs(title = &#39;분기별 서울시 인구수 변화 추이&#39;,
         x = &#39;연도&#39;, y = &#39;인구수&#39;) +
    facet_grid(~tempqrt) </code></pre>
<p><img src="/post/2020-04-16-seoulpop3_files/figure-html/unnamed-chunk-7-4.png" width="100%" />
<br></p>
<p>  서울의 인구는 2010년 4분기에 잠시 상승하였다가 2011년을 기점으로 지속적으로 하락하고 있는것을 확인할 수 있습니다. 경제성장의 둔화, 라이프 스타일의 변화 같은 요인으로 인한 인구의 감소일까요? 추측은 할 수 있어도 이를 뒷받침할 근거가 없기 때문에 섣불리 판단할 수는 없을 것 같습니다. 서울의 인구하락의 요인이 무엇일지 문득 궁금증이 생기네요.</p>
<p>다음으로 성별에 따른 동향을 살펴보겠습니다.
<br></p>
</div>
<div id="성별간-인구-동향" class="section level3">
<h3>성별간 인구 동향</h3>
<pre class="r"><code>library(reshape2)
# 성별간 인구 
sum_seouldata %&gt;%
    select(GIGAN, NAMJA_1, YEOJA_1) %&gt;%
    reshape2::melt(id.vars = c(&#39;GIGAN&#39;)) %&gt;%
    ggplot(aes(x = GIGAN, y = value, group = variable)) +
    geom_line(aes(color = variable)) +
    geom_point(color = &#39;red&#39;) +
    geom_text(aes(label = value), hjust = &#39;inward&#39;, vjust = &#39;inward&#39;, size = 2, angle = 15) +
    theme(title = element_text(face = &#39;bold&#39;, size = 15)) +
    theme(axis.text.x = element_text(angle = 45, size = 7)) +
    theme(axis.title.x = element_text(size = 15)) +
    theme(axis.title.y = element_text(size = 15)) +
    scale_color_discrete(&quot;성별&quot;, labels = c(&#39;male&#39;, &#39;female&#39;)) +
    labs(title = &#39;연도-분기별 서울시 성별간 인구수 변화 추이 비교 &#39;,
         x = &#39;연도-분기&#39;, y = &#39;인구수&#39;) </code></pre>
<p><img src="/post/2020-04-16-seoulpop3_files/figure-html/unnamed-chunk-8-1.png" width="100%" />
<br></p>
<p>  성별에 따른 인구수의 동향을 살펴보자면 앞서 상관분석에서 남성과 여성의 상관계수가 0.9 이상이였던 것을 확인 했듯이 두 성별 모두 시간에 따른 추세는 비슷해 보입니다. 하지만 그래프에서 남성의 인구가 여성보다 더욱 가파르게 하락하는 것을 볼 수 있습니다. 더불어 서울 내 여성의 인구수가 남성보다 대략 20만명 많은 것을 볼 수 있네요.<br />
<br></p>
</div>
<div id="고령-인구-동향" class="section level3">
<h3>고령 인구 동향</h3>
<pre class="r"><code># 연도별 인구
sum_seouldata %&gt;%
    group_by(year) %&gt;%
    summarise(mean_pop = round(mean(N_65SEISANGGORYEONGJA), 0)) %&gt;%
    ggplot(aes(x = year %&gt;% as.factor(), y = mean_pop, group = 1)) +
    geom_point(color = &#39;red&#39;) +
    geom_line() +
    geom_text(aes(label = mean_pop), hjust = &#39;inward&#39;, vjust = -1, size = 4, angle = 15) +
    theme(title = element_text(face = &#39;bold&#39;, size = 25)) +
    theme(axis.text.x = element_text(angle = 45)) +
    theme(axis.title.x = element_text(size = 15)) +
    theme(axis.title.y = element_text(size = 15)) +
    labs(title = &#39;서울시 연평균 고령인구수 변화 추이&#39;,
         x = &#39;연도&#39;, y = &#39;고령인구수&#39;) </code></pre>
<p><img src="/post/2020-04-16-seoulpop3_files/figure-html/unnamed-chunk-9-1.png" width="100%" /></p>
<pre class="r"><code># 연도-분기별 인구
sum_seouldata %&gt;%
    ggplot(aes(x = GIGAN, y = N_65SEISANGGORYEONGJA, group = 1)) +
    geom_point(color = &#39;red&#39;) +
    geom_line() +
    geom_text(aes(label = N_65SEISANGGORYEONGJA), hjust = &#39;inward&#39;, vjust = &#39;inward&#39;, size = 2) +
    theme(title = element_text(face = &#39;bold&#39;, size = 20)) +
    theme(axis.text.x = element_text(angle = 45)) +
    theme(axis.title.x = element_text(size = 15)) +
    theme(axis.title.y = element_text(size = 15)) +
    labs(title = &#39;연도-분기별 서울시 고령인구수 변화 추이&#39;,
         x = &#39;연도-분기&#39;, y = &#39;고령인구수&#39;) </code></pre>
<p><img src="/post/2020-04-16-seoulpop3_files/figure-html/unnamed-chunk-9-2.png" width="100%" /></p>
<pre class="r"><code>sum_seouldata %&gt;%
    mutate(tempyear = paste(year, &#39;년&#39;)) %&gt;%
    ggplot(aes(x = qrt %&gt;% as.factor(), y = N_65SEISANGGORYEONGJA, group = 1)) +
    geom_point(color = &#39;red&#39;) +
    geom_line() +
    geom_text(aes(label = N_65SEISANGGORYEONGJA), hjust = &#39;inward&#39;, vjust = &#39;inward&#39;, size = 2) +
    theme(title = element_text(face = &#39;bold&#39;, size = 20)) +
    theme(axis.title.x = element_text(size = 15)) +
    theme(axis.title.y = element_text(size = 15)) +
    labs(title = &#39;연도-분기별 서울시 고령인구수 변화 추이&#39;,
         x = &#39;연도-분기&#39;, y = &#39;고령인구수&#39;) +
    facet_grid(~tempyear) </code></pre>
<p><img src="/post/2020-04-16-seoulpop3_files/figure-html/unnamed-chunk-9-3.png" width="100%" /></p>
<pre class="r"><code># 분기별 인구수 변화
sum_seouldata %&gt;%
    mutate(tempqrt = paste(qrt, &#39;분기&#39;)) %&gt;%
    ggplot(aes(x =year %&gt;% as.factor(), y = N_65SEISANGGORYEONGJA, group = 1)) +
    geom_point(color = &#39;red&#39;) +
    geom_line() +
    geom_text(aes(label = N_65SEISANGGORYEONGJA), hjust = &#39;inward&#39;, vjust = -1, size = 3, angle = 15) +
    theme(title = element_text(face = &#39;bold&#39;, size = 25)) +
    theme(axis.text.x = element_text(angle = 45)) +
    theme(axis.title.x = element_text(size = 15)) +
    theme(axis.title.y = element_text(size = 15)) +
    labs(title = &#39;분기별 서울시 고령인구수 변화 추이&#39;,
         x = &#39;연도-분기&#39;, y = &#39;고령인구수&#39;) +
    facet_grid(~tempqrt)  </code></pre>
<p><img src="/post/2020-04-16-seoulpop3_files/figure-html/unnamed-chunk-9-4.png" width="100%" />
<br></p>
<p>  65세 이상의 인구수는 시간과 상관 없이 해마다 꾸준히 증가해 오고 있었습니다. 그래프의 기울기의 변화가 거의 없는것으로 보아 증가하는 요인이 특정 기간에 있는것이 아닌것으로 보여지는데요. 전체 인구가 감소하는 와중에 65세 이상 노령인구는 증가한다는 것은 그만큼 서울에 젊은 사람들이 줄어들고 있다는 것으로 바라볼 수 있을 것 같습니다. 저출산과 고령화라는 단어가 더욱 와닿게 느껴지네요.
<br></p>
</div>
<div id="자치구별-변화" class="section level3">
<h3>자치구별 변화</h3>
<pre class="r"><code>library(scales)
library(zoo)
# 연도별 변화
seouldata %&gt;%
    ggplot(aes(x = as.factor(year), y = GYE_1, group = 1)) +
    geom_line() +
    geom_point(color = &#39;red&#39;) +
    geom_text(aes(label = GYE_1), hjust = &#39;inward&#39;, vjust = &#39;inward&#39;, size = 2.5, angle = 45, check_overlap = T) +
    theme(plot.title = element_text(face = &#39;bold&#39;, size = 20)) +
    theme(axis.title.x = element_text(face = &#39;bold&#39;, size = 15)) +
    theme(axis.title.y = element_text(face = &#39;bold&#39;, size = 15)) +
    theme(axis.text.x = element_text( size = 10, angle = 45)) +
    scale_y_continuous(labels=scales::comma) +
    facet_wrap(~JACHIGU) +
    labs(title = &#39;서울시 자치구별 연간 인구 변화 추이&#39;,
         x = &#39;연도&#39;, y = &#39;인구&#39;)</code></pre>
<p><img src="/post/2020-04-16-seoulpop3_files/figure-html/unnamed-chunk-10-1.png" width="100%" /></p>
<pre class="r"><code># 자치구별 인구 Boxplot
seouldata %&gt;%
    ggplot(aes(x = JACHIGU, y = GYE_1, col = JACHIGU)) +
    geom_boxplot() + 
    theme(plot.title = element_text(face = &#39;bold&#39;, size = 20)) +
    theme(axis.title.x = element_text(face = &#39;bold&#39;, size = 15)) +
    theme(axis.title.y = element_text(face = &#39;bold&#39;, size = 15)) +
    theme(axis.text.x = element_text(size = 10, angle = 45)) +
    theme(legend.position = &#39;none&#39;) + 
    scale_y_continuous(labels=scales::comma) +
    labs(title = &#39;서울시 자치구별 인구 Boxplot&#39;,
         x = &#39;자치구&#39;, y = &#39;인구&#39;)</code></pre>
<p><img src="/post/2020-04-16-seoulpop3_files/figure-html/unnamed-chunk-10-2.png" width="100%" /></p>
<pre class="r"><code># 연도별 변화(인구순 정렬)
seouldata$JACHIGU &lt;- seouldata$JACHIGU %&gt;% as.character() %&gt;% as.factor()
popLevels &lt;- seouldata %&gt;%
    group_by(JACHIGU) %&gt;%
    summarise(mean_pop = mean(GYE_1)) %&gt;%
    arrange(desc(mean_pop)) %&gt;%
    ungroup() %&gt;%
    select(JACHIGU) %&gt;%
    sapply(., function(x){as.character(x)}) %&gt;%
    as.character()
seouldata_ordered &lt;- arrange(transform(seouldata, JACHIGU = factor(JACHIGU, levels = popLevels)), JACHIGU)

seouldata_ordered %&gt;%
    ggplot(aes(x = as.factor(year), y = GYE_1, group = 1)) +
    geom_line() +
    geom_point(color = &#39;red&#39;, size = .5) +
    theme(plot.title = element_text(face = &#39;bold&#39;, size = 15)) +
    theme(axis.title.x = element_text(face = &#39;bold&#39;, size = 10)) +
    theme(axis.title.y = element_text(face = &#39;bold&#39;, size = 10)) +
    theme(axis.text.y = element_text(size = 3)) + 
    theme(axis.text.x = element_text(size = 3, angle = 90)) +
    theme(strip.text.x = element_text(size = 5)) + 
    scale_y_continuous(labels=scales::comma) +
    zoo::facet_free(~JACHIGU) +
    labs(title = &#39;서울시 자치구별 연간 인구 변화 추이 (평균인구수 기준 조정)&#39;,
         x = &#39;연도&#39;, y = &#39;인구&#39;) </code></pre>
<p><img src="/post/2020-04-16-seoulpop3_files/figure-html/unnamed-chunk-10-3.png" width="100%" />
<br></p>
<p>  자치구별 인구수 역시 송파와 강서를 제외한 모든 지역이 하락하는 모습을 볼 수 있습니다. 인구 하락의 요인이 어느 특정 지역에 있는것이 아닌 전반적인 추세에 있다는 것을 의미하는것 같네요.
<br></p>
<hr />
<p>  지금까지 서울시 열린데이터 광장에서 제공하는 서울시 주민등록인구 통계 데이터를 다뤄 보았습니다. 분석을 통해 서울시의 인구 감소를 직접 확인하였는데요. 언론에서 말하는 인구 절벽이니 저출산 고령화 등과 같은 키워드들이 좀 더 크게 와닿게 되는것 같습니다. 이번 분석에선 인구 하락 현상에 대한 시각화를 진행하였지만, 훗날 기회가 되면 인구 하락의 여러 요인들을 수집하여 더욱 고도화된 분석을 진행해 볼까 합니다.</p>
</div>
</div>
</div>
